// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmtmpsdlomfnrqribvtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdG1wc2Rsb21mbnJxcmlidnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTk2ODEsImV4cCI6MjA3MjkzNTY4MX0.5sykV_xWLNCXLmRBF5lyrzexo6V5g-2unkD1SoJ3Ec4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});